#!/bin/bash
# This restore script is adapted to Yunohost >=2.4

# The parameter $1 is the backup directory location dedicated to the app
backup_dir=$1

# The parameter $2 is the id of the app instance ex: ynhexample__2
app=$2

# Get old parameter of the app
domain=$(sudo yunohost app setting $app domain)
path=$(sudo yunohost app setting $app path)
admin_wordpress=$(sudo yunohost app setting $app admin)
language=$(sudo yunohost app setting $app language)
is_public=$(sudo yunohost app setting $app is_public)

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app
if [[ ! $? -eq 0 ]]; then
    echo "There is already an app on this URL : $domain$path" | sudo tee /dev/stderr
    exit 1
fi

# Restore sources & data
final_path=/var/www/$app

if [ -d $final_path ]; then
    echo "There is already a directory: $final_path " | sudo tee /dev/stderr
    exit 1
fi
sudo cp -a "${backup_dir}/var/www/$app" $final_path


db_pwd=$(sudo yunohost app setting $app mysqlpwd)
db_user=$app
sudo yunohost app initdb $db_user -p $db_pwd
sudo su -c "mysql -u $db_user -p$db_pwd $app < ${backup_dir}/db.sql"
sudo rm -f "${backup_dir}/db.sql"
sudo sed -i -e "s/'DB_USER', *'[^']*'/'DB_USER', '$app'/g" $final_path/wp-config.php
sudo sed -i -e "s/'DB_NAME', *'[^']*'/'DB_NAME', '$app'/g" $final_path/wp-config.php

# Set permissions
sudo chown -R www-data:www-data $final_path

# Restore conf files
conf=/etc/nginx/conf.d/$domain.d/$app.conf
if [ -f $conf ]; then
    echo "There is already a nginx conf file at this path: $conf " | sudo tee /dev/stderr
    exit 1
fi
sudo cp -a "${backup_dir}/conf/nginx.conf" $conf

# Reload Nginx
sudo service nginx reload

# Set ssowat config
if [ "$is_public" = "No" ];
then
	sudo yunohost app setting $app skipped_uris -d
fi
sudo yunohost app ssowatconf
